apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-mainpage-standard-1
  namespace: toolkit
spec:
  gateways:
    - toolkit/toolkit-gateway-1
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /main-page
        - uri:
            prefix: /
      name: main-page
      route:
        - destination:
            host: main-page
            port:
              number: 8080
